# Generated by Django 6.1.1 on 2026-09-28 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='foodtrack.restaurante'),
        ),
    ]
