# Generated by Django 6.1.1 on 2026-09-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrack', '0003_usuario_restaurante_nulo_apenas_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desperdicio',
            name='descricao',
            field=models.CharField(max_length=300),
        ),
    ]
